# Generated by Django 3.0.3 on 2020-02-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('instituicao', models.CharField(max_length=100)),
                ('hora', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Escolaridade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(max_length=100)),
                ('instituicao', models.CharField(max_length=100)),
                ('grau', models.CharField(max_length=100)),
                ('inicio', models.DateField()),
                ('fim', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100)),
                ('empresa', models.CharField(max_length=100)),
                ('inicio', models.DateField()),
                ('fim', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesse', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=100)),
                ('tipo', models.IntegerField(choices=[(1, 'Linguagem'), (2, 'Framework'), (3, 'Ferramenta'), (4, 'Outra Tecnologia')], default=1)),
                ('icone', models.ImageField(blank=True, null=True, upload_to='icones_tecnologias')),
            ],
        ),
        migrations.CreateModel(
            name='Sobre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('cep', models.IntegerField()),
                ('telfone', models.CharField(max_length=9)),
                ('ddd', models.IntegerField()),
                ('email', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('icone', models.ImageField(upload_to='foto_perfil')),
            ],
        ),
    ]
