# Generated by Django 3.0.3 on 2020-03-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_auto_20200222_0425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sobre',
            old_name='icone',
            new_name='foto',
        ),
        migrations.RenameField(
            model_name='sobre',
            old_name='telfone',
            new_name='telefone',
        ),
        migrations.AddField(
            model_name='sobre',
            name='cidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sobre',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
