# Generated by Django 3.0.3 on 2020-03-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0003_auto_20200305_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='hora',
            new_name='horas',
        ),
        migrations.RenameField(
            model_name='sobre',
            old_name='descricao',
            new_name='sobre_mim',
        ),
        migrations.AddField(
            model_name='escolaridade',
            name='nota',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='atual',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sobre',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sobre',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sobre',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sobre',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sobre',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='tipo',
            field=models.IntegerField(choices=[(1, 'Linguagem'), (2, 'Framework'), (3, 'Ferramenta'), (4, 'Outra Tecnologia'), (5, 'workflow')], default=1),
        ),
    ]
