# Generated by Django 3.0.3 on 2020-03-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0004_auto_20200306_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='web_icon',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
