# Generated by Django 3.0.3 on 2020-03-06 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0005_skill_web_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='web_icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
