# Generated by Django 3.0.3 on 2020-03-06 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0007_auto_20200306_1311'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Interesse',
            new_name='Objetivo',
        ),
        migrations.RenameField(
            model_name='objetivo',
            old_name='interesse',
            new_name='objetivo',
        ),
    ]
